#kubeadm --v=5 join --config /root/config.yaml --ignore-preflight-errors=all
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: ${K8S_CONTROL_PLANE_ENDPOINT}:6443
    token: ${KUBEADM_TOKEN}
    unsafeSkipCAVerification: true
    caCertHashes:
    - ${CA_CERT_HASH}
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 0.0.0.0
    bindPort: 6443
  certificateKey: ${JOIN_CERT_KEY}
