apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
    node-labels: "node-type=rook"
discovery:
  bootstrapToken:
    apiServerEndpoint: ${K8S_API_ENDPOINT}:6443
    token: ${KUBEADM_TOKEN}
    caCertHashes:
    - ${CA_CERT_HASH}
