config:
  description: This example project works on clustered LXD. However, the
    bridge must be configured in Linux first. In this specific case I use the
    lxdbrige bridge that is created in the system and configured. And use the 
    project profile, which by default uses this bridge for the network.
    This is the most production mode, as it allows the network infrastructure
    to be configured in the systems with certain needs for each project.
    And use this bridge for LXD containers, as well as each kubernetes node
    that works on top of it.
  lxd:
    projectName: ncdc
  kubernetes:
    clusterName: ncdc
    version: 1.22.0
    podSubnet: 10.0.0.0/16
    controlPlaneEndpointDomain: ncdc.pt
  instances:
  - instance:
    lxd:
      name: ncdc-kmaster
      image: ubuntu:22.04
      profile: ncdc-kmaster
    kubernetes:
      type: master
  - instance:
    lxd:
      name: ncdc-kworker1
      image: ubuntu:22.04
      profile: ncdc-kworker1
    kubernetes:
      type: worker
  - instance:
    lxd:
      name: ncdc-kworker2
      image: ubuntu:22.04
      profile: ncdc-kworker2
    kubernetes:
      type: worker
