config:
  description: "This example project works on an LXD cluster, although it 
   also works with an isolated LXD host. For it to work, the bridge not
   managed by LXD must be created on all hosts belonging to the LXD cluster
   and that it allows the containers configured on the various LXD hosts
   to communicate with each other. In this specific case I use the
   lxdbrige bridge that is created on the systems and configured. And use 
   the project profiles, which by default uses this bridge for the network.
   This is the mode used in production, as it allows the network infrastructure
   to be configured on systems with specific needs for each project.
   "
  lxd:
    projectName: ncdc
  kubernetes:
    clusterName: ncdc
    version: 1.22.0
    podSubnet: 10.0.0.0/16
    controlPlaneEndpointDomain: ncdc.pt
  instances:
  - instance:
    lxd:
      name: ncdc-kmaster
      image: ubuntu:22.04
      profile: ncdc-kmaster
    kubernetes:
      type: master
  - instance:
    lxd:
      name: ncdc-kworker1
      image: ubuntu:22.04
      profile: ncdc-kworker1
    kubernetes:
      type: worker
  - instance:
    lxd:
      name: ncdc-kworker2
      image: ubuntu:22.04
      profile: ncdc-kworker2
    kubernetes:
      type: worker
