config:
  description: This example project works on clustered LXD. However, the
    bridge must be configured in Linux first. In this specific case I use the
    lxdbrige bridge that is created in the system and configured. And use the
    default project profile, which by default uses this bridge for the network.
  lxd:
    projectName: ncdc
  kubernetes:
    clusterName: ncdc
    version: 1.24.0
    podSubnet: 10.9.0.0/16
    controlPlaneEndpointDomain: ncdc.pt
  instances:
  - instance:
    lxd:
      name: project-kmaster
      image: ubuntu:22.04
      profile: k8s-kmaster
    kubernetes:
      type: master
  - instance:
    lxd:
      name: project-kworker1
      image: ubuntu:22.04
      profile: k8s-kworker1
    kubernetes:
      type: worker
  - instance:
    lxd:
      name: project-kworker2
      image: ubuntu:22.04
      profile: k8s-kworker2
    kubernetes:
      type: worker
