config:
  description: Test yaml config file
  lxd:
    projectName: ncdc
  kubernetes:
    clusterName: ncdc
    version: 1.24.0
    podSubnet: 10.9.0.0/16
    controlPlaneEndpointDomain: ncdc.pt
  instances:
  - instance:
    lxd:
      name: project-kmaster
      image: ubuntu:22.04
      profile: k8s-kmaster
    kubernetes:
      type: master
  - instance:
    lxd:
      name: project-kworker1
      image: ubuntu:22.04
      profile: k8s-kworker1
    kubernetes:
      type: worker
  - instance:
    lxd:
      name: project-kworker2
      image: ubuntu:22.04
      profile: k8s-kworker2
    kubernetes:
      type: worker
