apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana-storage
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
